import { z } from 'zod';

/**
 * Content Status Enum
 * Tracks the lifecycle of content generation
 */
export const ContentStatusSchema = z.enum([
  'draft',      // Initial state, not yet processed
  'generating', // Currently being generated by AI
  'completed',  // Successfully generated
  'failed'      // Generation failed
]);

export type ContentStatus = z.infer<typeof ContentStatusSchema>;

/**
 * Generation Options Schema
 * Configures tone, style, and formatting for AI-generated content
 */
export const GenerationOptionsSchema = z.object({
  tone: z.enum([
    'professional',
    'casual',
    'formal',
    'friendly',
    'authoritative',
    'conversational'
  ]).default('professional'),

  style: z.enum([
    'informative',
    'persuasive',
    'educational',
    'storytelling',
    'technical',
    'creative'
  ]).default('informative'),

  wordCount: z.number().min(100).max(10000).default(1000),

  includeIntro: z.boolean().default(true),
  includeConclusion: z.boolean().default(true),

  sectionCount: z.number().min(1).max(20).default(5),

  formatting: z.object({
    useMarkdown: z.boolean().default(true),
    includeTOC: z.boolean().default(false), // Table of Contents
    useHeadings: z.boolean().default(true)
  }).default({})
});

export type GenerationOptions = z.infer<typeof GenerationOptionsSchema>;

/**
 * Content Metadata Schema
 * SEO and metadata information for blog articles
 */
export const ContentMetadataSchema = z.object({
  keywords: z.array(z.string()).min(1).max(10),

  targetAudience: z.string().optional(),

  seoDescription: z.string().max(160).optional(),

  category: z.string().optional(),

  tags: z.array(z.string()).optional(),

  primaryKeyword: z.string().optional()
});

export type ContentMetadata = z.infer<typeof ContentMetadataSchema>;

/**
 * Article Section Schema
 * Represents a single section within a blog article
 */
export const ArticleSectionSchema = z.object({
  heading: z.string().min(1),
  content: z.string().min(1),
  order: z.number().min(0)
});

export type ArticleSection = z.infer<typeof ArticleSectionSchema>;

/**
 * Blog Article Schema
 * Complete structure for a generated blog article
 */
export const BlogArticleSchema = z.object({
  id: z.string().uuid().optional(),

  title: z.string().min(10).max(200),

  introduction: z.string().min(50).optional(),

  sections: z.array(ArticleSectionSchema).min(1),

  conclusion: z.string().min(50).optional(),

  metadata: ContentMetadataSchema,

  status: ContentStatusSchema.default('draft'),

  generatedAt: z.date().optional(),

  wordCount: z.number().optional()
});

export type BlogArticle = z.infer<typeof BlogArticleSchema>;

/**
 * Content Request Schema
 * Input schema for requesting blog/article generation
 * This will be used in API Step bodySchema
 */
export const ContentRequestSchema = z.object({
  topic: z.string().min(3).max(500).describe('The main topic or title for the article'),

  keywords: z.array(z.string()).min(1).max(10).describe('SEO keywords to include'),

  targetAudience: z.string().optional().describe('Who is the target audience?'),

  additionalContext: z.string().optional().describe('Additional context or specific requirements'),

  options: GenerationOptionsSchema.optional()
});

export type ContentRequest = z.infer<typeof ContentRequestSchema>;

/**
 * Content Response Schema
 * Response schema for content generation
 * This will be used in API Step responseSchema
 */
export const ContentResponseSchema = z.object({
  id: z.string().uuid(),

  article: BlogArticleSchema,

  status: ContentStatusSchema,

  message: z.string().optional(),

  generationTimeMs: z.number().optional()
});

export type ContentResponse = z.infer<typeof ContentResponseSchema>;

/**
 * Error Response Schema
 * Used when content generation fails
 */
export const ErrorResponseSchema = z.object({
  error: z.string(),
  code: z.string().optional(),
  details: z.record(z.any()).optional()
});

export type ErrorResponse = z.infer<typeof ErrorResponseSchema>;
